apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-conf
data:
  haproxy.cfg: |
    global
        #chroot      /var/lib/haproxy
        pidfile     /var/run/haproxy.pid
        maxconn     4000
        daemon
        # turn on stats unix socket
        #stats socket /var/lib/haproxy/stats

    #---------------------------------------------------------------------
    # common defaults that all the 'listen' and 'backend' sections will
    # use if not designated in their block
    #---------------------------------------------------------------------
    defaults
        mode                    http
        option http-server-close
        option forwardfor       except 127.0.0.0/8
        option                  redispatch
        retries                 3
        timeout http-request    10s
        timeout queue           1m
        timeout connect         10s
        timeout client          1m
        timeout server          1m
        timeout http-keep-alive 10s
        timeout check           10s
        maxconn                 30000
    
        #stats enable
        #stats show-node
        #stats uri  /haproxy?stats
        #stats realm Haproxy\ Statistics
        #stats auth admin:So0shy@nt


    frontend ft_http
        mode http
        bind *:80
        option forwardfor
        #errorfile 503 /etc/haproxy/errorfiles/farabixo-503.html
        #errorfile 500 /etc/haproxy/errorfiles/farabixo-503.html
        #errorfile 404 /etc/haproxy/errorfiles/index2.html
        #errorfile 500 /etc/haproxy/errorfiles/index2.html
        default_backend web_http

    #---------------------------------------------------------------------
    # round robin balancing between the various backends
    #---------------------------------------------------------------------
    backend web_http
        mode http
        ## If add healthcheck URL
        #option httpchk HEAD /healthcheck
        balance roundrobin
        option forwardfor
        # cookie ASP.NET_SessionId prefix nocache
        server srv1 192.168.20.154:2132  check
        server srv2 192.168.20.154:2131  check
        server srv3 192.168.20.154:2130  check
        server srv4 192.168.20.154:2129  check

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: oms-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: oms-server
    spec:
      containers:
      - name: oms-server
        image: haproxy
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/local/etc/haproxy/ # mount nginx-conf volumn to /etc/nginx
          readOnly: true
          name: haproxy-cfg
      volumes:
      - name: haproxy-cfg
        configMap:
          name: haproxy-conf # place ConfigMap `nginx-conf` on /etc/nginx
          items:
            - key: haproxy.cfg
              path: haproxy.cfg

---
apiVersion: v1
kind: Service
metadata:
  name: oms-server
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: oms-server