apiVersion: v1
kind: Service
metadata:
  labels:
    app: broker
  name: as-cluster-1
  selfLink: /api/v1/namespaces/aerospike-test/services/aerospike
  namespace: aerospike-broker-farabixo
spec:
  externalIPs:
    - 192.168.20.151
    - 192.168.20.152
    - 192.168.20.153
  ports:
    - name: service
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: broker