apiVersion: v1
kind: Service
metadata:
  labels:
    app: aerospike
    cluster: as-cluster-0
  name: as-cluster-1
  namespace: aerospike-operator
  ownerReferences:
    - apiVersion: aerospike.travelaudience.com/v1alpha2
      blockOwnerDeletion: true
      controller: true
      kind: AerospikeCluster
      name: as-cluster-0
      uid: 45cf7398-60e8-11e9-95f6-005056afc8ad
spec:
  externalIPs:
    - 192.168.110.134
    - 192.168.110.135
    - 192.168.110.136
  ports:
    - name: service
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: heartbeat
      port: 3002
      protocol: TCP
      targetPort: 3002
  selector:
    app: aerospike
    cluster: as-cluster-0
