---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: logstash
  namespace: elasticsearch
  labels:
    app: logstash
spec:
  replicas: 1
  template:
      metadata:
        labels:
          app: logstash
      spec:
        containers:
        - name: fluentd-logstash
          image: docker.io/logstash:5
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9400
          command:
          - "/usr/share/logstash/bin/logstash"
          - "-e"
          - "input { tcp { port => 9400 } } output { elasticsearch { hosts => 'http://elasticsearch:9200' } }"
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
          - mountPath: /usr/share/logstash/data
            name: data
          - mountPath: /var/lib/logstash
            name: lib
        nodeSelector:
          glusterfs: "storage-host"
        restartPolicy: Always
        volumes:
        - name: data
          emptyDir: {}
        - name: lib
          emptyDir: {}
--- 
apiVersion: v1
kind: Service
metadata:
  labels:
    logging-infra: support
  name: logstash
  namespace: elasticsearch
spec:
  ports:
    - name: logstash-forward
      port: 9400
      protocol: TCP
      targetPort: 9400
  selector:
    app: logstash