apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /var/exports/openshift/pv0001
    server: 192.168.56.11
  persistentVolumeReclaimPolicy: Recycle